# Site settings
title: NGAGE CONTENT
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: ""
url: "http://ngagecontent.com"

# Build settings
markdown: kramdown
permalink: pretty

# Links to include in site navigation
links:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Blog
    url: /blog
  - title: Subscribe
    url: /subscribe
  - title: Contact
    url: /contact

# Google analytics
google_analytics:   UA-62439730-1

# Social media links
social:
  twitter:  https://twitter.com/ngagecontent
  facebook: https://www.facebook.com/ngagecontent
  linkedin: 
  google_plus:
  instagram: 
