# Site settings
title: NGAGE CONTENT
email: jd@ngagecontent.com
description: "NgageContent is an inbound marketing services and technology company focused on helping businesses drive more qualified leads to their sales team."
baseurl: ""
url: "http://ngagecontent.com"

# Build settings
markdown: kramdown
permalink: pretty

# Links to include in site navigation
links:
  - title: Home
    url: /
  - title: Blog
    url: /blog
  - title: Subscribe
    url: /subscribe
  - title: Contact
    url: /contact

# Google analytics
google_analytics:   UA-62439730-1

# Social media links
social:
  twitter:  https://twitter.com/ngagecontent
  facebook: https://www.facebook.com/ngagecontent
  linkedin: https://www.linkedin.com/company/ngagecontent
  google_plus: https://plus.google.com/u/0/b/109715903752747703433/109715903752747703433/about/p/pub
  instagram: 
